# Site settings
title: Jeremy McDuffie
subtitle: Ruby on Rails + Front-end Dev + UX
author: Jeremy McDuffie
description: |
  A developer blog covering topics for Ruby on Rails and front-end development with an emphasis on
  good UX.
username: jmmcduffie

url: "http://jmmcduffie.com"
baseurl:
feedurl: http://feeds.feedblitz.com/jmmcduffie
permalink: /blog/:title/

titlecase: true
date_format: "%-d %B %Y"
category_dir: blog/categories
