# Site settings
title: jmmcduffie.com
author: Jeremy McDuffie
description: >-
  The #indieweb home of Jeremy McDuffie.
url: "https://jmmcduffie.com"
permalink: /blog/:title/
github_username: jmmcduffie
linkedin_username: jmmcduffie

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-avatar

# Theme settings
minima:
  date_format: "%-d %B %Y"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
