# Site settings
title: jmmcduffie.com
author: Jeremy McDuffie
description: The personal domain of Jeremy McDuffie.
username: jmmcduffie

url: "http://jmmcduffie.com"
feedurl: "/atom.xml"
permalink: /blog/:title/

titlecase: true
date_format: "%-d %B %Y"
category_dir: blog/categories
